XinSu-Jiang/Haemeok-backend

- src/main/java/com/jdc/recipe_service/config/SecurityConfig.java
- src/main/java/com/jdc/recipe_service/security/oauth/OAuth2AuthenticationSuccessHandler.java
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
- src/main/resources/static/index.html
- OAuth2AuthenticationSuccessHandler 수정:
- Referer 기반으로 로컬(localhost)과 운영(www.haemeok.com) 환경 분기 처리
- server.forward-headers-strategy: framework 설정 application.yml, application-prod.yml에 추가
- Swagger 경로 프록시 설정을 위한 Nginx 설정 추가
- Spring Security에서 HTTPS 강제 설정 (.requiresSecure)
> OAuth2 로그인 리디렉션 로직 수정 및 HTTPS 설정 적용

- src/main/java/com/jdc/recipe_service/controller/UserController.java
- src/main/java/com/jdc/recipe_service/jwt/JwtAuthenticationFilter.java
- src/main/resources/static/index.html
- Access Token 만료 시 401 Unauthorized 응답 반환 로직 추가
- 프론트에서 해당 응답 감지 후 Refresh 로직 실행을 위해 구현
- api/users/me 삭제 (api/me로 관리)
> JWT 토큰 만료 시 401 응답 처리 추가

- src/main/java/com/jdc/recipe_service/controller/AuthController.java
- src/main/java/com/jdc/recipe_service/security/oauth/OAuth2AuthenticationSuccessHandler.java
- OAuth2 로그인 성공 시 RefreshToken을 HttpOnly 쿠키로 저장하도록 변경
- /api/token/refresh 요청 시 쿠키에서 refreshToken 추출하여 accessToken 재발급
- 로컬 테스트 위해 setSecure(true) 임시 주석 처리
> OAuth2 로그인 시 RefreshToken 쿠키로 전달 및 재발급 API 구현

- src/main/java/com/jdc/recipe_service/domain/dto/fridge/RefrigeratorItemSummaryDto.java
- src/main/java/com/jdc/recipe_service/domain/dto/ingredient/IngredientSummaryDto.java
- src/main/java/com/jdc/recipe_service/mapper/IngredientMapper.java
- src/main/java/com/jdc/recipe_service/service/IngredientService.java
- src/main/java/com/jdc/recipe_service/service/RefrigeratorItemService.java
1. **IngredientSummaryDto 수정**  
- 기존 필드에서 `inFridge` 제거  
- `unit` 필드 유지 (프론트 요청 반영)  
- 패키지: `domain/dto/ingredient/IngredientSummaryDto.java`
2. **RefrigeratorItemSummaryDto 수정**  
- DTO 구조를 중첩(`ingredients: {...}`) 없이 flat하게 변경  
- `ingredientId`, `name`, `category`, `imageUrl`, `unit` 필드만 포함  
- 패키지: `domain/dto/fridge/RefrigeratorItemSummaryDto.java`
3. **IngredientMapper 정리**  
- `toSummaryDto(…)` 삭제 후, `IngredientSummaryDto` 생성 로직 반영  
- 사용되지 않는 import·메서드 제거
4. **RefrigeratorItemService 수정**  
- `getMyItems()`에서 새 DTO 구조에 맞춰 매핑  
- 중복된 DTO 참조 제거
5. **RefrigeratorItemController 검증**  
- `/api/me/fridge/items` 응답이 flat한 JSON 배열로 반환되는지 확인
6. **테스트 및 문서 업데이트**  
- 변경된 DTO 스펙에 맞춰 테스트 수정  
- API 문서 예시 갱신
- **수정**  
- `domain/dto/ingredient/IngredientSummaryDto.java`  
- …
> Ingredient 조회 JSON 출력 양식 Front 요구사항에 맞게 수정

- src/main/java/com/jdc/recipe_service/config/SecurityConfig.java
- src/main/java/com/jdc/recipe_service/controller/CalendarController.java
- src/main/java/com/jdc/recipe_service/domain/dto/calendar/CookingRecordSummaryDto.java
- src/main/java/com/jdc/recipe_service/service/CookingRecordService.java
- 기존 GET /api/me/calendar/{date} → GET /api/me/calendar?date=YYYY-MM-DD (RequestParam 방식)
- CookingRecordSummaryDto에 아래 필드만 반환하도록 변경
- recipeId
- recipeTitle
- recipeImageUrl (S3 키 → URL로 변환)
- savings
- /api/me/calendar/** 추가
> 캘린더 API date 파라미터 변경·레코드 요약 필드 추가·보안 설정 업데이트Feature/calendar

- src/main/java/com/jdc/recipe_service/controller/RecipeController.java
- src/main/java/com/jdc/recipe_service/service/CookingRecordService.java
- src/main/java/com/jdc/recipe_service/service/RecipeRatingService.java
- src/main/java/com/jdc/recipe_service/service/RecipeService.java
- DDL 마이그레이션으로 recipe_ratings.recipe_id 및 cooking_records.recipe_id, cooking_records.rating_id 외래키에 ON DELETE CASCADE 적용
- JPA 엔티티에서 cascade = REMOVE / orphanRemoval = true 어노테이션 제거
- CookingRecordService.deleteByRatingId, RecipeService.deleteRecipe 내 명시적 삭제 로직 제거
- 레시피/평점/요리기록 삭제 흐름을 DB에 위임하여 코드 단순화
- DB 마이그레이션
- recipe_ratings.recipe_id → ON DELETE CASCADE
- cooking_records.recipe_id → ON DELETE CASCADE
- cooking_records.rating_id → ON DELETE CASCADE
- Recipe , RecipeRating , CookingRecord 클래스의 @OneToMany(cascade=REMOVE, orphanRemoval=true) 제거
- 평점 삭제 시 요리기록 수동 삭제(deleteByRatingId) 호출 제거
- 레시피 삭제 시 평점·요리기록·이미지 등 연관 엔티티 삭제 로직 내 요리기록 삭제 부분 제거
> DB에 CASCADE 적용으로 서비스 코드 수정

- src/main/java/com/jdc/recipe_service/RecipeServiceApplication.java
- src/main/java/com/jdc/recipe_service/config/SecurityConfig.java
- src/main/java/com/jdc/recipe_service/controller/AuthController.java
- src/main/java/com/jdc/recipe_service/domain/entity/RefreshToken.java
- src/main/java/com/jdc/recipe_service/domain/entity/common/BaseTimeEntity.java
- src/main/java/com/jdc/recipe_service/domain/repository/RefreshTokenRepository.java
- src/main/java/com/jdc/recipe_service/scheduler/RefreshTokenCleanupScheduler.java
- src/main/java/com/jdc/recipe_service/security/oauth/OAuth2AuthenticationSuccessHandler.java
- 사용자당 최대 4개의 리프레시 토큰 발급
- 초과 시 오래된 토큰부터 즉시 삭제
- 매일 자정에 만료된 토큰 레코드를 일괄 삭제하는 스케줄러 도입
- /api/token/logout/all 엔드포인트 추가
- Repository 메서드 확장
- deleteByUserId(userId) : 전체 로그아웃
- deleteAllByExpiredAtBefore(now) : 만료 토큰 청소
- BaseTimeEntity 에 @PrePersist/@PreUpdate 로 생성·수정일 자동 처리
- 기존 @EnableJpaAuditing 대신에 코드 레벨에서 관리
- @EnableJpaAuditing 및 @EnableScheduling 활성화
> 리프레시 토큰 최대 수 제한 및 초과분 삭제 로직 추가

- src/main/java/com/jdc/recipe_service/config/SecurityConfig.java
- src/main/java/com/jdc/recipe_service/security/oauth/OAuth2AuthenticationSuccessHandler.java
1. **OAuth2AuthenticationSuccessHandler**  
- 기존 `java.servlet.http.Cookie` → `ResponseCookie`로 교체  
- Secure, HttpOnly, Path, Max-Age뿐 아니라 `SameSite=None` 을 명시해 크로스-사이트 리디렉션 시에도 쿠키가 차단되지 않도록 설정  
2. **SecurityConfig**  
- 모든 요청에 CORS 헤더를 보장하기 위해 전역 `CorsFilter` 빈 추가  
- 기존 `corsConfig()` 는 유지하여 preflight 요청과 시큐리티 체인 내 CORS 처리는 그대로 수행
> api/refresh response 헤더 설정

- src/main/java/com/jdc/recipe_service/controller/AuthController.java
- src/main/java/com/jdc/recipe_service/security/oauth/OAuth2AuthenticationSuccessHandler.java
- OAuth2AuthenticationSuccessHandler
- javax.servlet.http.Cookie 대신 Spring의 ResponseCookie 사용
- Secure, HttpOnly 외에 SameSite=None 옵션을 명시하여 쿠키가 크로스-사이트에서도 허용되도록 수정
> api/refresh cookie 관련 수정

- src/main/java/com/jdc/recipe_service/controller/AuthController.java
- src/main/java/com/jdc/recipe_service/domain/dto/calendar/CalendarDaySummaryDto.java
- src/main/java/com/jdc/recipe_service/service/CookingRecordService.java
- CalendarDaySummaryDto에 totalCount, firstImageUrl 필드 추가
- CookingRecordService에 S3 이미지 URL 생성 메서드(generateImageUrl) 추가 및 @Value 프로퍼티 주입
- getMonthlySummary 로직 수정: 일별 레코드 건수 조회 및 가장 오래된 레코드의 이미지 URL 조회 후 DTO에 반영
> 달력 요약 API에 일별 레시피 건수 및 첫 번째 이미지 URL 추가

- src/main/java/com/jdc/recipe_service/service/RecipeSearchService.java
- 특정 레시피 조회 시 `ingredients.mapToDouble(RecipeIngredientDto::getCalories).sum()` 구문에서
`getCalories()`가 null인 경우 NPE가 발생했습니다.
- 또한, 총 칼로리(totalCalories)는 소수점 둘째 자리까지 버림(truncate) 처리해야 합니다.
1. `.mapToDouble(i -> i.getCalories() != null ? i.getCalories() : 0.0)` 로 null 안전 처리  
2. `BigDecimal.setScale(2, RoundingMode.DOWN)` 으로 총 칼로리 소수점 둘째 자리 버림 적용  
- null인 custom_calorie, master ingredient calorie 값 모두 정상 조회 확인  
- 소수점 셋째 자리 이상이 있는 레시피에서 총 칼로리가 둘째 자리까지 잘려서 반환되는 것 확인  
- `RecipeSearchService.getRecipeDetail()`  
- 반환 DTO인 `RecipeDetailDto.totalCalories`
> hotfix(recipe-search-service): 칼로리 null 처리 및 총 칼로리 소수점 둘째 자리 버림 적용

- src/main/java/com/jdc/recipe_service/config/WebConfig.java
- src/main/resources/application.yml
- 프록시(ALB/Nginx) 뒤에서 넘어오는 X-Forwarded-* 헤더를
HTTP 요청 뿐만 아니라 SockJS/WebSocket 핸드셰이크에도
올바르게 반영하기 위해 설정을 조정
1. application.yml
- `server.forward-headers-strategy` 를 `native` 로 변경  
- 톰캣 RemoteIpValve 활성화를 위한 설정 추가
- `tomcat.remote-ip-header: X-Forwarded-For`
- `tomcat.protocol-header: X-Forwarded-Proto`
- `tomcat.internal-proxies: 127\.0\.0\.1|192\.168\.0\.\d+`
2. `WebConfig` 클래스 수정
- `ForwardedHeaderFilter` 빈 등록으로 Spring MVC 및
SockJS 핸드셰이크에도 X-Forwarded 헤더 적용
- 애플리케이션 로그에서 RemoteIpValve 활성화 여부  
- 브라우저 Network 탭에서 `wss://…/ws/notifications` 로 연결되는지  
- 프록시 레벨(SSL/ALB/Nginx)에서 Upgrade 헤더가 통과되는지
> config: 톰캣 native 헤더 처리 및 WebSocket 핸드셰이크용 ForwardedHeaderFilter 추가

- src/main/java/com/jdc/recipe_service/config/JwtHandshakeInterceptor.java
- src/main/java/com/jdc/recipe_service/config/SecurityConfig.java
- src/main/java/com/jdc/recipe_service/config/WebConfig.java
- src/main/java/com/jdc/recipe_service/config/WebSocketConfig.java
- src/main/java/com/jdc/recipe_service/config/WebSocketSecurityConfig.java
- src/main/java/com/jdc/recipe_service/jwt/JwtTokenProvider.java
- src/main/resources/application.yml
- src/main/resources/static/test-ws.html
- WebSocket(STOMP) 핸드쉐이크 단계부터 JWT 기반 인증·인가를 적용, 메시지 레벨 보안 강화
1. **JwtTokenProvider 개선**
- CustomUserDetailsService 주입
- getAuthentication(String token) 메서드 추가
- 토큰에서 userId 추출 → CustomUserDetailsService#loadUserByUsername() 호출 → UsernamePasswordAuthenticationToken 생성
2. **JwtHandshakeInterceptor 신설**
- 핸드쉐이크 시점에 쿼리파라미터(?token=…) 또는 Authorization 헤더에서 JWT 추출·검증
- 검증 성공 시 tokenProvider.getAuthentication(token) 호출 → attributes.put("user", principal)
3. **WebSocketConfig 수정**
- @RequiredArgsConstructor 로 JwtTokenProvider 주입
- /ws/notifications 엔드포인트에 JwtHandshakeInterceptor 등록
- setAllowedOriginPatterns을 로컬(http://localhost:5173)·프로덕션(https://www.haemeok.com) 도메인으로 제한
4. **WebSocketSecurityConfig 신설**
- @EnableWebSocketMessageSecurity + @Configuration
- STOMP 메시지 보안 적용
- /app/** (SEND) → 인증 …
> feat(ws): JWT 기반 WebSocket 인증·인가 및 메시지 보안 구성 추가

- src/main/java/com/jdc/recipe_service/config/PrincipalHandshakeHandler.java
- src/main/java/com/jdc/recipe_service/config/WebSocketConfig.java
- registry.addEndpoint() 에서 setHandshakeHandler 를 두 번 호출하던 부분 제거
- JwtHandshakeInterceptor 를 먼저 등록하고, 단일 PrincipalHandshakeHandler 로 인증된 Principal 설정
- 핸드쉐이크 단계에서 attributes 에 담긴 “user” 속성을 WebSocket Principal 로 연결
> fix(websocket): 핸드쉐이크 핸들러 중복 등록 제거 및 PrincipalHandshakeHandler 적용

- src/main/java/com/jdc/recipe_service/config/WebSocketSecurityConfig.java
- 핸드셰이크 인증 성공 후에도 STOMP 연결이 실패하는 문제를 해결하기 위해 WebSocketSecurityConfig의 인바운드 메시지 규칙을 단순화
- 기존의 복잡한 메시지 경로별 규칙 대신, 핸드셰이크를 통해 인증된 사용자는 모든 메시지 유형을 허용하도록 .anyMessage().authenticated()로 변경하여 문제를 해결.
> feat(websocket): 메시징 보안 규칙 단순화로 연결 오류 해결

- src/main/java/com/jdc/recipe_service/controller/NotificationController.java
- src/main/java/com/jdc/recipe_service/domain/repository/NotificationRepository.java
- src/main/java/com/jdc/recipe_service/service/NotificationService.java
**제목**: 알림 조회 API에 페이징 기능 추가
**변경 사항**  
1. Repository 조회 메서드가 `Pageable` 을 받아 `Page<Notification>` 을 반환  
2. Service 계층에서 `Page<NotificationDto>` 를 반환  
3. Controller에서 Spring Data `Pageable` 을 지원하여  
- `GET /api/notifications?page=<번호>&size=<개수>&sort=createdAt,desc&read=<true|false>` 형태로 호출 가능  
4. 기본 페이지 크기 20, `createdAt` 내림차순 정렬
**내용** 
- **NotificationRepository**  
- `findByUserIdOrderByCreatedAtDesc`,  
`findByUserIdAndIsReadFalseOrderByCreatedAtDesc`,  
`findByUserIdAndIsReadTrueOrderByCreatedAtDesc` 메서드 반환 타입을 `List<Notification>` → `Page<Notification>` 으로 변경  
- 모든 조회 메서드에 `Pageable` 파라미터 추가
- **NotificationService**  
- `getNotifications`, `getUnreadNotifications`, `getReadNotifications` 메서드 오버로드하여 `Pageable` 인자를 받도록 수정  
- `Page<Notification>` → `Page<NotificationDto>` 로 매핑
- …
> feat(notification): 알림 API 페이징 기능 추가

- src/main/java/com/jdc/recipe_service/jwt/JwtAuthenticationFilter.java
- JwtAuthenticationFilter.shouldNotFilter()에 `/ws/notifications` 경로 추가  
- WebSocket 핸드쉐이크 요청이 JWT 필터를 우회하도록 설정  
- 프론트에서 쿠키 기반 인증 정보(withCredentials)로 정상 처리되도록 수정
> feat(ws): 핸드쉐이크 경로 JWT 필터 예외 처리

- src/main/java/com/jdc/recipe_service/service/AuthService.java
- OAuth2AuthorizedClientManager는 인증되지 않은 흐름에서도 Authentication principal 객체를 요구하므로, 이 값이 없어 예외가 발생
- AnonymousAuthenticationToken을 임시 principal로 제공하여 OAuth2 클라이언트 인증이 정상적으로 진행되도록 수정
> fix(auth): AuthService의 ClientAuthorizationRequiredException 해결

- src/main/java/com/jdc/recipe_service/config/SecurityConfig.java
- SecurityConfig에 OAuth2AuthorizedClientRepository(HttpSessionOAuth2AuthorizedClientRepository) 빈 등록
- SecurityConfig의 authorizedClientManager 빈을 DefaultOAuth2AuthorizedClientManager로 대체
> feat(auth): 익명 인증 객체 적용

- build.gradle
- src/main/java/com/jdc/recipe_service/config/SecurityConfig.java
- src/main/java/com/jdc/recipe_service/service/AuthService.java
변경 파일
- src/main/java/com/jdc/recipe_service/config/SecurityConfig.java
- src/main/java/com/jdc/recipe_service/service/AuthService.java
주요 변경 사항
1. SecurityConfig.java  
- 기존 `authorizedClientService` / `authorizedClientManager` 빈 주석 처리  
- `accessTokenResponseClient()` 빈 추가 (`DefaultAuthorizationCodeTokenResponseClient` 사용)  
- HttpSessionOAuth2AuthorizedClientRepository 관련 코드를 더 이상 사용하지 않도록 정리  
2. AuthService.java  
- `AuthorizedClientManager` 호출을 완전히 제거  
- `OAuth2AccessTokenResponseClient<OAuth2AuthorizationCodeGrantRequest>` 주입 후  
- `OAuth2AuthorizationRequest`·`OAuth2AuthorizationResponse` 직접 생성  
- `DefaultAuthorizationCodeTokenResponseClient` 통해 액세스 토큰 교환  
- 교환된 토큰으로 `CustomOAuth2UserService`를 직접 호출해 사용자 정보 로드
> refactor(auth): OAuth2 토큰 교환 로직 리팩토링 및 안정화

- src/main/java/com/jdc/recipe_service/config/JwtHandshakeInterceptor.java
- src/main/java/com/jdc/recipe_service/config/WebSocketConfig.java
로컬 환경(localhost)에서 운영 API 서버로 WebSocket 연결 시, 브라우저의 SameSite=Lax 쿠키 정책으로 인해 accessToken 쿠키가 전송되지 않음 
이로 인해 JwtHandshakeInterceptor가 토큰을 찾지 못하고 핸드셰이크를 거부하여 실시간 알림 기능이 동작하지 않음
프론트엔드 변경 (요청사항): WebSocket 연결 URL에 accessToken을 쿼리 파라미터(?token=...)로 담아 보내도록 수정
- JwtHandshakeInterceptor 수정: URL 쿼리 파라미터에서 토큰을 우선적으로 읽도록 로직을 추가함 
기존 쿠키 방식은 하위 호환성을 위해 Fallback으로 유지함
또한, 일관적인 관리를 위해 Spring @Component로 등록함
- WebSocketConfig 수정: 인터셉터를 new로 직접 생성하는 대신, Spring 컨테이너가 관리하는 Bean을 주입받아 사용하도록 변경하여 의존성 주입 원칙을 따르도록 함
> fix(websocket): WebSocket 핸드셰이크 인증 로직 수정

- src/main/java/com/jdc/recipe_service/service/OpenAiClientService.java
- src/main/java/com/jdc/recipe_service/util/PromptBuilder.java
- src/main/java/com/jdc/recipe_service/util/UnitService.java
1. **OpenAiClientService.initializeSystemPrompt()**  
- `unitMapping`(재료별 기본 단위 매핑) 부분을 제거하고  
- 오직 `allowedUnits`(허용 단위 목록)만 System Prompt에 전달하도록 수정
2. **PromptBuilder.buildPrompt()**  
- `unitService.mappingByIngredient()`를 이용해 **요청된 재료**에 한정된 매핑(`mappingForRequest`)만 추출  
- 그 결과를 `[특별 지시]`의 “다음 재료에 대해서만 단위를 강제 사용하세요” 항목으로 포함
3. **UnitService**  
- `mappingByIngredient()` 메서드 추가로 프롬프트 빌더에서 재료별 매핑을 조회할 수 있게 함
- System Prompt에는 이제 ‘허용 단위 목록’만 노출됨을 확인
- 실제 레시피 생성 시, 사용자 요청 재료에 대해서만 지정한 단위로 강제되는지 테스트
- `mappingForRequest`가 빈 문자열일 때는 “단위 강제” 블록이 출력되지 않도록 추가 조건을 달아도 좋습니다.
> refactor: 시스템 프롬프트 전역 재료-단위 매핑 제거, PromptBuilder에 요청별 단위 매핑 추가

- src/main/java/com/jdc/recipe_service/util/PromptBuilder.java
- src/main/java/com/jdc/recipe_service/util/UnitService.java
- UnitService
- CSV 로드 시 정규화(소문자/trim) 및 중복 제거
- 허용 단위를 공백 없는 CSV로 캐싱하여 토큰 절약
- mappingAsStringFor: 요청 재료 중 csv 존재 항목만 {이름:단위}로 반환(중복 제거, fallback 제거)
- PromptBuilder
- known(우리 재료)만 단위 매핑 노출, unknown은 허용 단위 목록으로 제한
- 단위 강제 규칙 7/8 분리 및 위반 시 실패 문구 추가
- 불필요 안내문 제거(토큰 절감)
- 재료 힌트는 known 재료에만 (단위) 표기
> feat(units,prompt): units.csv 엄격 적용 및 프롬프트 경량화

- .github/workflows/deploy.yml
- build.gradle
- ecs-task-definition-template.json
- src/main/java/com/jdc/recipe_service/config/AnthropicConfig.java
- src/main/java/com/jdc/recipe_service/service/OpenAiClientService.java
- src/main/java/com/jdc/recipe_service/service/RecipeService.java
- src/main/java/com/jdc/recipe_service/util/ClaudeClientService.java
- src/main/resources/application-prod.yml
기존 OpenAI(GPT-4-Turbo) 모델의 높은 비용과 응답 시간으로 인해 발생하는 Vercel 타임아웃 문제를 해결하기 위해, AI 레시피 생성 모델을 Anthropic사의 Claude 3 Sonnet으로 교체합니다.
주요 변경 사항:
- RestTemplate을 사용하여 Claude API를 직접 호출하는 ClaudeClientService 신규 구현
- RestTemplate의 타임아웃 설정을 위한 RestTemplateConfig 추가
- RecipeService에서 AI 서비스 호출 대상을 ClaudeClientService로 변경
- 기존 OpenAiClientService 및 관련 설정은 유지 (향후 A/B 테스트나 롤백을 위해)
> feat: ai model claude
