- build.gradle
- src/main/java/com/jdc/recipe_service/config/SecurityConfig.java
build.gradle 과 securityConfig 수정하였습니다.
http://localhost:8080/swagger-ui.html
또는 
http://localhost:8080/swagger-ui/index.html 로 확인가능 
도메인은 http://www.haemeok.com/swagger-ui.html
또는 
http://www.haemeok.com/swagger-ui/index.html
> swagger 적용

- src/main/java/com/jdc/recipe_service/config/SecurityConfig.java
configuration.setAllowedOrigins(Arrays.asList("http://localhost:5173"));
->
configuration.setAllowedOrigins(Arrays.asList(
"http://localhost:5173",
"https://www.haemeok.com"
)); 로 수정
> SecurityConfig에 cors허용 수정

- src/main/java/com/jdc/recipe_service/config/SecurityConfig.java
- .cors(Customizer.withDefaults()) 삭제
> SecurityConfig에 cors허용 수정2

- src/main/java/com/jdc/recipe_service/controller/RecipeController.java
- src/main/java/com/jdc/recipe_service/service/UserService.java
> 비회원 fallback 설정

- src/main/java/com/jdc/recipe_service/security/oauth/OAuth2AuthenticationSuccessHandler.java
> local 환경에서 로그인 위해 successHandler 수정

- .github/workflows/deploy.yml
- ecs-task-definition-template.json
주요 변경 사항
- RDS DB URL 변경
- S3 버킷 이름 및 region 수정
- application-prod.yml 및 task-definition 환경 변수 반영
- GitHub Actions 관련 환경변수 키와 값 수정
> AWS 리소스 설정 및 환경 변수 수정

- src/main/resources/static/index.html
- src/main/resources/static/login/index.html
-프론트의 index.html와의 충돌으로/resources/static/index.html 삭제
> 기존 로그인 테스트용 index.html 삭제

- src/main/java/com/jdc/recipe_service/handler/GlobalExceptionHandler.java
- src/main/java/com/jdc/recipe_service/service/RecipeIngredientService.java
- src/main/java/com/jdc/recipe_service/service/RecipeStepService.java
오류메세지 추가
레시피 수정 오류 수정 
delete를 바로 flush해서 중복처리
> 오류 메세지 추가 & 레시피 수정 로직 수정

- src/main/java/com/jdc/recipe_service/controller/CommentController.java
- src/main/java/com/jdc/recipe_service/controller/RecipeController.java
- src/main/java/com/jdc/recipe_service/controller/RecipeUploadController.java
- src/main/java/com/jdc/recipe_service/controller/UserController.java
- src/main/java/com/jdc/recipe_service/domain/dto/recipe/MyRecipeSummaryDto.java
- src/main/java/com/jdc/recipe_service/domain/repository/RecipeFavoriteRepository.java
- src/main/java/com/jdc/recipe_service/exception/CommentAccessDeniedException.java
- src/main/java/com/jdc/recipe_service/handler/GlobalExceptionHandler.java
- src/main/java/com/jdc/recipe_service/service/RecipeService.java
- src/main/java/com/jdc/recipe_service/service/UserService.java
-모든 컨트롤로에서 유저fallback 에서 인증으로 변경
-인증 체크 로직 추가
> 모든 컨트롤로에서 유저fallback 에서 인증으로 변경 후 인증체크

- src/main/java/com/jdc/recipe_service/controller/RecipeController.java
- src/main/java/com/jdc/recipe_service/controller/UserController.java
- src/main/java/com/jdc/recipe_service/domain/dto/recipe/MyRecipeSummaryDto.java
- src/main/java/com/jdc/recipe_service/domain/dto/recipe/RecipeSimpleDto.java
- src/main/java/com/jdc/recipe_service/domain/entity/Recipe.java
- src/main/java/com/jdc/recipe_service/domain/repository/RecipeQueryRepository.java
- src/main/java/com/jdc/recipe_service/domain/repository/RecipeQueryRepositoryImpl.java
- src/main/java/com/jdc/recipe_service/service/RecipeService.java
- src/main/java/com/jdc/recipe_service/service/UserService.java
-남이 작성한 레시피 보기 추가 
-내가 작성한 레시피랑 별도 처리  api 다름
-레시피 전체간단 조회 수정
+ 요리시간
+ 별점
+ 별점수
> 남의 레시피 보기 추가 & 레시피 전체간단 조회 수정

- src/main/java/com/jdc/recipe_service/config/SecurityConfig.java
- src/main/java/com/jdc/recipe_service/controller/RecipeController.java
- src/main/java/com/jdc/recipe_service/controller/RecipeUploadController.java
- src/main/java/com/jdc/recipe_service/domain/dto/recipe/RecipeImageKeyUpdateRequest.java
- src/main/java/com/jdc/recipe_service/domain/dto/recipe/RecipeUserCreateRequestDto.java
- src/main/java/com/jdc/recipe_service/domain/dto/recipe/RecipeWithImageUploadRequest.java
- src/main/java/com/jdc/recipe_service/domain/dto/recipe/step/RecipeStepUserRequestDto.java
- src/main/java/com/jdc/recipe_service/domain/dto/url/FileInfoRequest.java
- src/main/java/com/jdc/recipe_service/domain/dto/url/PresignedUrlResponse.java
- src/main/java/com/jdc/recipe_service/domain/dto/url/PresignedUrlResponseItem.java
- src/main/java/com/jdc/recipe_service/service/RecipeService.java
- src/main/java/com/jdc/recipe_service/service/RecipeUploadService.java
- 레시피 생성과 동시에 파일 정보를 넘겨줌
- url값과 파일키를 응답값으로 받음
- s3에 저장 후 레시피에 이미지 정보 수정
> 레시피 생성 + 이미지

- src/main/java/com/jdc/recipe_service/controller/CommentController.java
- src/main/java/com/jdc/recipe_service/service/CommentService.java
- src/main/java/com/jdc/recipe_service/service/RecipeService.java
- src/main/resources/application.yml
-댓글 조회에서 like->likeCount로 수정
-디시타입 조회와 태그 조회에 좋아요 정렬 추가
> 좋아요 정렬 추가 및 like->likeCount로 전체 적용

- src/main/java/com/jdc/recipe_service/controller/RecipeSearchController.java
- src/main/resources/application-prod.yml
-application-prod.yml 에서 server : forward-headers-strategy 값을 framework -> native 수정
-레시피 검색 조건에서 페이지 기본값 설정 추가
> application-prod.yml 수정 & 페이지 기본값 설정

- src/main/resources/application-prod.yml
> application-prod.yml 수정

- src/main/java/com/jdc/recipe_service/config/SecurityConfig.java
- src/main/resources/application.yml
공개 엔드포인트 수정 및 Pre-flight(OPTIONS) 허용
> swagger 관련 securityConfig 수정

- build.gradle
- src/main/java/com/jdc/recipe_service/controller/RecipeSearchController.java
- src/main/java/com/jdc/recipe_service/exception/ErrorCode.java
-opensearch gradle 추가 
-레시피 검색 조건 title -> q로 변경
> opensearch gradle 추가 및 검색 조건 title -> q로 변경

- src/main/java/com/jdc/recipe_service/domain/dto/recipe/RecipeSimpleDto.java
- src/main/java/com/jdc/recipe_service/domain/repository/RecipeQueryRepositoryImpl.java
- src/main/java/com/jdc/recipe_service/domain/repository/RecipeRepository.java
- 레시피 simpleDto에  유저 profileimage 추가
> simpleDto 에 profileimage 추가

- src/main/java/com/jdc/recipe_service/config/SecurityConfig.java
- SecurityConfig  GET "/api/search/**" 허용
> SecurityConfig  GET "/api/search/**" 허용

- src/main/java/com/jdc/recipe_service/opensearch/controller/OpenSearchAdminController.java
- 인덱스 최초생성 (다음에 삭제나 주석처리) ‼️필수‼️
> 인덱스 최초생성 (다음에 삭제나 주석처리)

- src/main/java/com/jdc/recipe_service/config/SecurityConfig.java
- SecurityConfig에  "/api/opensearch/**" 추가
> SecurityConfig에  "/api/opensearch/**" 추가

- src/main/java/com/jdc/recipe_service/config/SecurityConfig.java
POST 권한 /api/ratings/recipe/* 추가
> 별점 관련 SecurityConfig 수정

- src/main/java/com/jdc/recipe_service/domain/entity/Ingredient.java
> entity에 칼로리 항목 추가

- .github/workflows/deploy.yml
- ecs-task-definition-template.json
- src/main/java/com/jdc/recipe_service/opensearch/config/OpenSearchConfig.java
- src/main/resources/application.yml
- deploy.yml & ecs_task_definition & yml 수정
- 깃허브 secrets에도 추가
-  OpenSearchConfig.java에서 호스트·포트·스킴 하드코딩 제거하고 @Value로 외부 주입
> 배포 파이프라인 수정 및 업데이트

- src/main/java/com/jdc/recipe_service/opensearch/controller/SearchController.java
> 재료 검색 prefix 조건 변경

- src/main/java/com/jdc/recipe_service/service/RecipeService.java
> 스텝 이미지 재수정

- src/main/java/com/jdc/recipe_service/opensearch/controller/SearchController.java
- src/main/java/com/jdc/recipe_service/opensearch/keyword/KeywordService.java
- src/main/java/com/jdc/recipe_service/opensearch/keyword/SearchKeyword.java
- src/main/java/com/jdc/recipe_service/opensearch/keyword/SearchKeywordRepository.java
- src/main/java/com/jdc/recipe_service/opensearch/service/OpenSearchService.java
- src/main/java/com/jdc/recipe_service/opensearch/service/OpenSearchSuggestionService.java
- src/main/java/com/jdc/recipe_service/opensearch/service/RecipeIndexingService.java
- 레시피 오픈서치 수정(아직 검색은 안합침) 
- 자동완성 구현
> 레시피 오픈서치 수정 & 자동완성 구현

- .github/workflows/deploy.yml
- src/main/java/com/jdc/recipe_service/service/RecipeSearchService.java
- 서버에서 색인은 되지만 화면에 뜨지않아 다시 미적용
> 오픈서치 다시 미적용

- src/main/java/com/jdc/recipe_service/opensearch/keyword/KeywordService.java
- src/main/java/com/jdc/recipe_service/opensearch/keyword/SearchKeyword.java
- src/main/java/com/jdc/recipe_service/opensearch/keyword/SearchKeywordRepository.java
- src/main/java/com/jdc/recipe_service/opensearch/service/OpenSearchService.java
- Transactional readonly 때문에 새로운 검색어로 검색시 오류나서 수정
- 추가 주석 삭제
> 오픈서치 키워드 수정

- src/main/java/com/jdc/recipe_service/controller/RecipeController.java
- src/main/java/com/jdc/recipe_service/domain/dto/comment/CommentDto.java
- src/main/java/com/jdc/recipe_service/domain/dto/recipe/step/RecipeStepIngredientRequestDto.java
- src/main/java/com/jdc/recipe_service/domain/entity/Recipe.java
- src/main/java/com/jdc/recipe_service/exception/ErrorCode.java
- src/main/java/com/jdc/recipe_service/mapper/StepIngredientMapper.java
- src/main/java/com/jdc/recipe_service/service/RecipeService.java
- src/main/java/com/jdc/recipe_service/service/RecipeStepService.java
> 레시피 수정 (이미지 포함)

- src/main/java/com/jdc/recipe_service/service/RecipeService.java
- 스텝 이미지가 S3에 실제 존재함에도 키 연결 전 isUnlinkedStepImage 조건에 걸려 매번 삭제되던 문제 수정
- 존재 여부만 확인 후 바로 updateStepImageKey → updateStatusToActive 순으로 처리하도록 로직 간소화 및 순서 변경
> 스텝 이미지 처리 수정

- src/main/java/com/jdc/recipe_service/controller/RecipeController.java
- src/main/java/com/jdc/recipe_service/domain/dto/recipe/RecipeWithImageUploadRequest.java
- src/main/java/com/jdc/recipe_service/domain/dto/recipe/ingredient/RecipeIngredientRequestDto.java
- src/main/java/com/jdc/recipe_service/domain/type/RobotType.java
- src/main/java/com/jdc/recipe_service/exception/CustomException.java
- src/main/java/com/jdc/recipe_service/mapper/RecipeIngredientMapper.java
- src/main/java/com/jdc/recipe_service/service/AdminRecipeService.java
- src/main/java/com/jdc/recipe_service/service/RecipeIngredientService.java
- src/main/java/com/jdc/recipe_service/service/RecipeService.java
- src/main/java/com/jdc/recipe_service/service/ReplicateService.java
- src/main/java/com/jdc/recipe_service/util/PromptBuilder.java
- replicate 프롬프트 & 생성 수정 (추후에 주석이나 재처리 필요)
- 4가지 모델마다 다른 프롬프트 설정 초기버전
> replicate 프롬프트 & 생성 수정

- src/main/java/com/jdc/recipe_service/opensearch/service/OpenSearchService.java
> url 주소 생성 수정

- src/main/java/com/jdc/recipe_service/opensearch/service/RecipeIndexingService.java
- 이러면 조회자체에서 늦게 조회되길래 다시 원상복구함
> 레시피 생성시 이미지 지연 수정 취소

- src/main/java/com/jdc/recipe_service/config/WebConfig.java
- src/main/java/com/jdc/recipe_service/service/AsyncImageService.java
> 이미지 타임아웃 처리

- src/main/java/com/jdc/recipe_service/service/AsyncImageService.java
> 이미지 타임아웃 처리3

- src/main/java/com/jdc/recipe_service/domain/repository/RecipeRepository.java
- src/main/java/com/jdc/recipe_service/service/AsyncImageService.java
> 이미지 타임아웃 처리4

- src/main/java/com/jdc/recipe_service/domain/repository/RecipeRepository.java
- src/main/java/com/jdc/recipe_service/service/AsyncImageService.java
> 이미지 타임아웃 처리6

- src/main/java/com/jdc/recipe_service/service/RecipeImageService.java
- 유저 생성 레시피 이미지키 주소 변경 recipes/... -> images/recipes/...
> hotfix: 유저 생성 레시피 이미지키 주소 변경

- src/main/java/com/jdc/recipe_service/controller/RecipeSearchController.java
- src/main/java/com/jdc/recipe_service/domain/dto/RecipeSearchCondition.java
- src/main/java/com/jdc/recipe_service/domain/repository/RecipeQueryRepository.java
- src/main/java/com/jdc/recipe_service/domain/repository/RecipeQueryRepositoryImpl.java
- src/main/java/com/jdc/recipe_service/opensearch/controller/SearchController.java
- src/main/java/com/jdc/recipe_service/opensearch/dto/RecipeDocument.java
- src/main/java/com/jdc/recipe_service/opensearch/service/OpenSearchService.java
- src/main/java/com/jdc/recipe_service/opensearch/service/RecipeIndexingService.java
- src/main/java/com/jdc/recipe_service/service/RecipeSearchService.java
- 기존 레시피 복합 검색에 isAiGenerated 파라미터 추가
- querydsl 과 opensearch 둘다 적용
> feat: 레시피 검색에 isAiGenerated 파라미터 필터 추가

- src/main/resources/application-prod.yml
- 호출 재시도 1회로 수정
- 타임아웃 10초로 조정
> hotfix: AI 호출 재시도 1회 및 타임아웃 10초로 조정

- build.gradle
- `spring-boot-starter-oauth2-jose` 제거
- `spring-boot-starter-oauth2-resource-server`만 남겨 JWT/JOSE 지원 활성화
> fix(deps): OAuth2 Resource Server 의존성 정리

- src/main/java/com/jdc/recipe_service/service/RecipeService.java
- src/main/java/com/jdc/recipe_service/util/PromptBuilder.java
> fix: PromptBuilder에 DB에 없는 재료에 customPrice·caloriesPerUnit 필드 추가

- build.gradle
- WebSocket 메시지 보안에 필요한 spring-security-messaging 모듈을 build.gradle에 추가
- AbstractSecurityWebSocketMessageBrokerConfigurer 관련 클래스 로드 오류 방지
> chore: spring-security-messaging 의존성 추가

- src/main/java/com/jdc/recipe_service/config/WebSocketConfig.java
- StompEndpointRegistry에 .setHandshakeHandler(new DefaultHandshakeHandler()) 적용
> feat(websocket): DefaultHandshakeHandler 추가

- src/main/java/com/jdc/recipe_service/service/AsyncImageService.java
- src/main/java/com/jdc/recipe_service/service/RecipeService.java
- **AsyncImageService**  
- 비동기 이미지 생성 메서드 리턴 타입을 `CompletableFuture<Void>`로 변경  
- 이미지 생성 성공/실패 시점에 맞춰 각각 `completedFuture`/`failedFuture` 반환  
- **RecipeService**  
- 기존 `TransactionSynchronizationManager.registerSynchronization` 블록 제거  
- `asyncImageService.generateAndUploadAiImageAsync(recipeId).thenRun(...)` 패턴 적용  
→ 이미지 업로드 완료 시점에만 `notificationService.createNotification(...)` 호출
> refactor(notification): AI 레시피 이미지 비동기 생성 및 알림 전송 로직 리팩토링

- src/main/java/com/jdc/recipe_service/controller/AuthController.java
- src/main/java/com/jdc/recipe_service/security/oauth/OAuth2AuthenticationSuccessHandler.java
1. 개발(local) 환경에서는 `Domain` 속성 없이 쿠키 발급하여 `localhost`에서 테스트 가능
2. 운영 환경(prod)에서는 `.haemeok.com` 도메인 설정으로 서브도메인 간 쿠키 공유 유지
3. AuthController 및 OAuth2AuthenticationSuccessHandler 리팩토링 포함
- AuthController 및 OAuth2AuthenticationSuccessHandler에 Spring `Environment` 주입
- `isLocal()` 메서드로 `local` 프로파일 체크
- 로컬 환경일 때 `.domain()` 호출 생략하여 localhost에 쿠키 저장
- 운영 환경일 때만 `.domain(".haemeok.com")` 설정 유지
- `ResponseCookie` 빌더 공통화 및 코드 정리
> feat: 프로파일별 쿠키 Domain 분기 적용

- src/main/java/com/jdc/recipe_service/config/SecurityConfig.java
- src/main/java/com/jdc/recipe_service/controller/LocalAuthController.java
- src/main/resources/application-prod.yml
- application.yml 에 명시된 redirect-uri 설정 제거  
- Spring Security 기본 redirect-uri 템플릿({currentRequestHost}/login/oauth2/code/{registrationId}) 사용
> feat(login): redirect-uri 동적 처리 지원

- src/main/java/com/jdc/recipe_service/config/SecurityConfig.java
- src/main/java/com/jdc/recipe_service/security/oauth/OAuth2AuthenticationSuccessHandler.java
주요 변경사항:
1. SecurityConfig.java:
- CSRF용 state 보존, redirect_uri Base64 인코딩 후 state에 포함
- 허용된 redirect URI 검증 로직 적용
2. OAuth2AuthenticationSuccessHandler.java:
- 콜백 시 전달된 composite state 파싱
- state에서 redirect_uri 복원 및 localhost 여부 판별
- 개발 환경: `/auth/callback`으로 accessToken, refreshToken 쿼리 파라미터로 전달
- 운영 환경: HttpOnly 쿠키(`refreshToken`, `accessToken`)로 전달 (도메인 `.haemeok.com`)
모든 Origin/Referer 기반 로직을 제거하고, state 파라미터 기반 분기 로직으로 통합하여 보안성과 유지보수성을 향상시킴
> feat(auth): state 기반 리디렉트 및 로컬 토큰 처리 지원

- src/main/java/com/jdc/recipe_service/util/PromptBuilder.java
- UnitService 주입을 통해 `unitService.mappingAsString()` 호출
- 로그에 강제 단위 매핑 정보 출력 (`🔧 강제 단위 매핑: …`)
- 프롬프트 특별 지시(`specialInstructions`)에 ‘재료별 단위 매핑 규칙’ 항목 추가
- AI 레시피 생성 시 DB에 저장된 재료의 단위가 올바르게 반영되는지 실시간 확인 필요
- 프롬프트에도 단위 매핑 규칙을 명시하여 AI가 잘못된 단위를 사용하지 않도록 강제
1. 서버 기동 및 레시피 요청 시 로그에 `🔧 강제 단위 매핑:` 메시지가 찍히는지 확인  
2. AI 생성 JSON 내 `unit` 필드들이 매핑 규칙대로 반환되는지 확인
> feat: PromptBuilder에 단위 매핑 로깅 및 프롬프트 반영 추가

- src/main/java/com/jdc/recipe_service/service/OpenAiClientService.java
- src/main/java/com/jdc/recipe_service/util/PromptBuilder.java
- PromptBuilder와 OpenAiClientService 원상복구
> revert: PromptBuilder 및 OpenAiClientService 원래대로 복원

- src/main/java/com/jdc/recipe_service/domain/dto/notification/NotificationDto.java
Notification 응답 구조 개편 (actorNickname, imageUrl 도입), content 삭제
> refactor(notification): NotificationDto 필드 수정

- src/main/java/com/jdc/recipe_service/domain/repository/RecipeQueryRepositoryImpl.java
- RecipeQueryRepositoryImpl.search() 에서 
- rLike.id.count() → rLike.id.countDistinct() 로 변경
- recipe.likes.size().castToNum() 대신 countDistinct 로 좋아요 개수 정확 집계
- composite sort용 getOrderSpecifiers() 적용으로 다중 sort 지원
> fix(recipe-search): 레시피 검색 좋아요 개수 중복 집계 버그 수정

- src/main/java/com/jdc/recipe_service/service/OpenAiClientService.java
- src/main/java/com/jdc/recipe_service/util/PromptBuilder.java
- src/main/java/com/jdc/recipe_service/util/UnitService.java
- cookingTime "10분"→정수 정규화. UnitService CSV 2컬럼만 파싱. known만 단위 매핑, 허용 단위 축소. OpenAI json_object 강제 및 최소 로그. 배포 후 모니터링.
> fix(ai): 500(JSON 파싱) 제거 및 프롬프트 정리

- src/main/java/com/jdc/recipe_service/service/OpenAiClientService.java
- src/main/java/com/jdc/recipe_service/util/PromptBuilder.java
- src/main/java/com/jdc/recipe_service/util/UnitService.java
- 임시 롤백. 단위/파싱 이슈 재현 및 재수정 전까지 안정화 목적.
> revert: 유닛 강제 고정하도록 수정전 롤백

- src/main/java/com/jdc/recipe_service/controller/LocalAuthController.java
- LocalAuthController에서 토큰 발급 시 ResponseCookie를 사용하도록 수정
- accessToken, refreshToken을 HttpOnly 쿠키로 내려주도록 변경
- SameSite=Lax, HttpOnly 옵션 추가하여 보안성 강화
- 기존 ResponseEntity<TokenResponseDTO> 응답 구조는 유지하여 개발 편의성 보장
> refactor(auth): Local 환경 쿠키 기반 토큰 발급 방식으로 수정
